"use server";
import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {getCurrentProfile,requireRole} from "@/lib/auth";import {createClient} from "@/lib/supabase/server";
const imageTypes=new Set(["image/jpeg","image/png","image/webp","image/gif"]),priceModes=new Set(["none","fixed","negotiable"]);
async function upload(id:string,file:File){if(!file.size)return null;if(file.size>5*1024*1024||!imageTypes.has(file.type))throw new Error();const path=`${id}/${crypto.randomUUID()}.${file.name.split(".").pop()||"webp"}`,supabase=await createClient();const{error}=await supabase.storage.from("subsidiary-media").upload(path,file,{contentType:file.type});if(error)throw error;return supabase.storage.from("subsidiary-media").getPublicUrl(path).data.publicUrl}
async function manager(id:string){const profile=await getCurrentProfile();if(!profile)return false;if(profile.role==="admin")return true;const supabase=await createClient();const{data}=await supabase.from("subsidiaries").select("responsible:employees!responsible_employee_id(code)").eq("id",id).maybeSingle();const person=Array.isArray(data?.responsible)?data.responsible[0]:data?.responsible;return person?.code===profile.employee_id}
function serviceInput(formData:FormData){const name=String(formData.get("name")??"").trim(),description=String(formData.get("description")??"").trim(),sort_order=Number(formData.get("sort_order")),price_mode=String(formData.get("price_mode")??"none"),raw=String(formData.get("price_value")??"").trim(),price_value=price_mode==="fixed"?raw:null;if(name.length<2||name.length>140||description.length>5000||!Number.isInteger(sort_order)||!priceModes.has(price_mode)||(price_mode==="fixed"&&(!price_value||price_value.length>120)))return null;return{name,description,sort_order,price_mode,price_value}}
export async function createSubsidiaryModal(formData:FormData){await requireRole(["admin"]);const name=String(formData.get("name")??"").trim(),responsible_employee_id=String(formData.get("responsible_employee_id")??""),description=String(formData.get("description")??"").trim(),location=String(formData.get("location")??"").trim();if(name.length<2||name.length>120||!/^[0-9a-f-]{36}$/i.test(responsible_employee_id)||description.length>5000||location.length>160)redirect("/subsidiarias?erro=dados");const supabase=await createClient();const{data,error}=await supabase.from("subsidiaries").insert({name,responsible_employee_id,description,location,status:"Ativa"}).select("id,code").single();if(error||!data)redirect("/subsidiarias?erro=salvar");const image=formData.get("image");if(image instanceof File&&image.size)try{await supabase.from("subsidiaries").update({image_url:await upload(data.id,image)}).eq("id",data.id)}catch{redirect(`/subsidiarias/${data.code}?erro=imagem`)}revalidatePath("/subsidiarias");redirect(`/subsidiarias/${data.code}?criado=1`)}
export async function addServiceModal(formData:FormData){await requireRole(["funcionario","admin"]);const subsidiary_id=String(formData.get("subsidiary_id")??""),code=String(formData.get("code")??""),input=serviceInput(formData);if(!(await manager(subsidiary_id)))redirect("/?erro=sem-permissao");if(!input)redirect(`/subsidiarias/${code}?erro=dados#servicos`);const supabase=await createClient();const{error}=await supabase.from("subsidiary_services").insert({subsidiary_id,...input});if(error)redirect(`/subsidiarias/${code}?erro=salvar#servicos`);revalidatePath(`/subsidiarias/${code}`);redirect(`/subsidiarias/${code}?salvo=1#servicos`)}
export async function updateServiceModal(formData:FormData){await requireRole(["funcionario","admin"]);const id=String(formData.get("id")??""),subsidiary_id=String(formData.get("subsidiary_id")??""),code=String(formData.get("code")??""),input=serviceInput(formData);if(!(await manager(subsidiary_id)))redirect("/?erro=sem-permissao");if(!input)redirect(`/subsidiarias/${code}?erro=dados#servicos`);const supabase=await createClient();const{error}=await supabase.from("subsidiary_services").update(input).eq("id",id).eq("subsidiary_id",subsidiary_id);if(error)redirect(`/subsidiarias/${code}?erro=salvar#servicos`);revalidatePath(`/subsidiarias/${code}`);redirect(`/subsidiarias/${code}?salvo=1#servicos`)}
